parameter r
Al2Klimov/trainee-go-sort pull request #28
Opened 2020-01-22 15:48 UTC by justinmueller05082000

fixes #12

2020-01-22 15:50 UTC, Al2Klimov requested changes

2020-01-22 15:50 UTC, Al2Klimov commented on main.go
> -
Not part of the task.

2020-01-23 08:59 UTC, Al2Klimov requested changes
* [x] `git reset --soft HEAD~$(git rev-list --count $(git merge-base HEAD master)..HEAD^)`
* [x] `git commit --amend --no-edit`
* [x] `git push -f origin feature/parameter-r-12`

2020-01-23 09:09 UTC, Al2Klimov requested changes
Write a test protocol.

2020-01-23 09:13 UTC, justinmueller05082000 commented
**Test protocol:**

**toSort.txt:**
```
5
4
6
7
9
0
2
1
5
7
8
4
3
```

**GO CODE:**
**Terminal:** `go run . -r toSort.txt` 
**Output:**
```
9
8
7
7
6
5
5
4
4
3
2
1
0
```


**SORT COMMAND:**
**Terminal:** `sort -r toSort.txt` 
**Output:**
```
9
8
7
7
6
5
5
4
4
3
2
1
0
```


**Conclusion:**
Both results are sorted and printed equally in the right and reverse order.

2020-01-23 09:17 UTC, merged